# ===========================================================================
#  µnleashed gateway sat
# ===========================================================================
#
# File:         firmware/tools/mkweb.py
# Module:       Build / the web payload that rides in the app image
#
# Purpose:      Gzips every page in firmware/web/, and the xterm.js assets
#               fetch_web.py cached, into one generated C++ source file in
#               firmware/src/webassets/ (ignored by git), with the header
#               that names them.
#
#               Why precompressed rather than compressed per request: there
#               is no built-in support in esp_http_server and there will not
#               be (IDF issue 18816 asked for it and was closed "Won't Do"),
#               and gzipping 290 KB on an ESP32 per page view would be
#               absurd. Brotli is not an option at all: browsers advertise
#               `br` only over HTTPS, and a captive portal cannot be HTTPS.
#
#               Why byte arrays rather than CMake's EMBED_FILES, which is
#               the tidier mechanism: EMBED_FILES generates .S files through
#               a cmake custom command, and PlatformIO drives the IDF
#               through its own SCons, which does not know how to produce
#               them ("Source `xterm_js.gz.S' not found"). An array is about
#               330 KB of source text nobody reads, which is the price of a
#               build that works. Worth re-trying if this ever moves to
#               idf.py.
#
#               Runnable alone:  python firmware/tools/mkweb.py
#
# Copyright 2026 - Robert Mech
# License:      GNU General Public License v3 or later
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
# ===========================================================================
import gzip
import io
import os
import sys

# Each asset: the C symbol it becomes, the URL it is served at, its media
# type, where it comes from ("cache" is what fetch_web.py fetched, "web" is
# ours, "joined" is built here), and its file name.
#
# URLs are short on purpose: every byte of one is a byte of the portal page,
# and the portal page is what every phone that joins fetches.
ASSETS = [
    ("xterm_js",  "/x.js",    "application/javascript", "cache",  "xterm.js"),
    ("xterm_css", "/x.css",   "text/css",               "cache",  "xterm.css"),
    ("fit_js",    "/f.js",    "application/javascript", "cache",  "fit.js"),
    ("term_html", "/t",       "text/html",              "web",    "term.html"),
    ("term_js",   "/t.js",    "application/javascript", "web",    "term.js"),
    ("style_css", "/s.css",   "text/css",               "web",    "style.css"),
    ("licences",  "/licence", "text/plain",             "joined", ""),
]

# The MIT notices, in the order they appear at /licence. Carrying them is
# what the notices ask for, and joining them is one URL for the portal.
LICENCES = [
    ("xterm.js 5.5.0 (https://xtermjs.org/)", "xterm.LICENSE"),
    ("@xterm/addon-fit 0.10.0", "fit.LICENSE"),
]

# What stands in for a missing third-party asset, so the portal can be
# worked on with no network. A release build refuses to compile against it.
STUB = {
    "xterm.js": b"window.Terminal=function(){throw new Error("
                b"'this gateway was built with no browser terminal');};\n",
    "xterm.css": b"/* placeholder: no xterm.css at build time */\n",
    "fit.js": b"window.FitAddon={FitAddon:function(){this.activate=function(){};"
              b"this.dispose=function(){};this.fit=function(){};}};\n",
    "xterm.LICENSE": b"placeholder: xterm.js was not fetched at build time\n",
    "fit.LICENSE": b"placeholder: the fit addon was not fetched at build time\n",
}

HEADER_TOP = """\
// ===========================================================================
//  GENERATED by firmware/tools/mkweb.py. Do not edit.
//
//  It writes this and web_assets.cpp beside it. These are the only names
//  that know what each page is served as.
//
//  Copyright 2026 - Robert Mech. SPDX-License-Identifier: GPL-3.0-or-later
// ===========================================================================
#pragma once
#include <cstdint>

"""


def read(path):
    with open(path, "rb") as f:
        return f.read()


def squash(data):
    """Level 9 and no timestamp, so an unchanged asset gives an unchanged
    blob and the build does not relink for nothing. GzipFile rather than
    gzip.compress, whose mtime argument is not in every Python this has to
    run on."""
    sink = io.BytesIO()
    with gzip.GzipFile(filename="", mode="wb", compresslevel=9,
                       fileobj=sink, mtime=0) as g:
        g.write(data)
    return sink.getvalue()


def build(fw, verified=True):
    """`verified` is false when fetch_web.py could not confirm the pinned
    packages this build. The cache may still hold files from an earlier
    build, and they may be the wrong version: an unverified build is marked
    as carrying a placeholder whatever is on disk, so a release build
    refuses it."""
    web = os.path.join(fw, "web")
    out = os.path.join(fw, "src", "webassets")
    os.makedirs(out, exist_ok=True)

    # Where fetch_web.py puts what it fetched: one flat directory, with a
    # stamp per package saying which version is in it.
    cache = os.path.join(fw, ".web-cache")
    if not os.path.isdir(cache):
        cache = ""
    stubbed = not verified

    rows = []
    blobs = {}
    total_raw = 0
    total_gz = 0

    for sym, url, mime, where, name in ASSETS:
        if where == "joined":
            parts = []
            for title, fname in LICENCES:
                src = os.path.join(cache, fname) if cache else ""
                if src and os.path.isfile(src):
                    body = read(src)
                else:
                    body = STUB.get(fname, b"")
                    stubbed = True
                head = "%s\n%s\n\n" % (title, "-" * len(title))
                parts.append(head.encode("utf-8"))
                parts.append(body)
                parts.append(b"\n\n")
            data = b"".join(parts)
        else:
            base = cache if where == "cache" else web
            src = os.path.join(base, name) if base else ""
            if src and os.path.isfile(src):
                data = read(src)
            elif name in STUB:
                data = STUB[name]
                stubbed = True
            else:
                sys.stderr.write("mkweb: missing %s\n" % src)
                return False

        gz = squash(data)
        blobs[sym] = gz
        rows.append((sym, url, mime, len(data), len(gz)))
        total_raw += len(data)
        total_gz += len(gz)

    # --- the header ------------------------------------------------------
    with open(os.path.join(out, "web_assets.h"), "w", encoding="utf-8") as f:
        f.write(HEADER_TOP)
        if stubbed:
            f.write(
                "// The browser terminal was NOT fetched when this was built.\n"
                "#define GW_WEB_STUB 1\n"
                "#ifdef GW_RELEASE\n"
                '#error "A release build needs the real browser terminal. '
                'Run tools/fetch_web.py with a network and build again."\n'
                "#endif\n"
                '#warning "No browser terminal in this image: '
                'tools/fetch_web.py could not fetch xterm.js."\n\n'
            )
        else:
            f.write("#define GW_WEB_STUB 0\n\n")

        f.write("struct WebAsset {\n"
                "    const char*    path;   // the URL it is served at\n"
                "    const char*    type;   // its media type\n"
                "    const uint8_t* gz;     // gzip; Content-Encoding: gzip\n"
                "    uint32_t       gzLen;\n"
                "    uint32_t       raw;    // before gzip, for the console\n"
                "};\n\n")
        # The size goes in the declaration: an extern array of unknown
        # bound is an incomplete type, and a range-for over one does not
        # compile.
        f.write("extern const WebAsset kWebAssets[%d];\n" % len(rows))
        f.write("constexpr unsigned kWebAssetCount = %d;\n\n" % len(rows))
        f.write("// What the whole payload costs the app image, at build:\n")
        f.write("//   raw %d bytes, gzipped %d bytes\n" % (total_raw, total_gz))
        f.write("#define GW_WEB_GZ_BYTES %d\n" % total_gz)

    # --- the bytes -------------------------------------------------------
    with open(os.path.join(out, "web_assets.cpp"), "w", encoding="utf-8") as f:
        f.write("// GENERATED by firmware/tools/mkweb.py. Do not edit.\n"
                "// Copyright 2026 - Robert Mech. "
                "SPDX-License-Identifier: GPL-3.0-or-later\n"
                '#include "web_assets.h"\n\n')
        for sym, _u, _m, _r, _g in rows:
            blob = blobs[sym]
            f.write("static const uint8_t k_%s[%d] = {\n" % (sym, len(blob)))
            for i in range(0, len(blob), 16):
                chunk = blob[i:i + 16]
                f.write("    " + ",".join("0x%02x" % b for b in chunk) + ",\n")
            f.write("};\n\n")
        f.write("const WebAsset kWebAssets[%d] = {\n" % len(rows))
        for sym, url, mime, raw, gz in rows:
            f.write('    { "%s", "%s", k_%s, %d, %d },\n' % (url, mime, sym, gz, raw))
        f.write("};\n")

    print("mkweb: %d assets, %d bytes raw, %d gzipped%s"
          % (len(rows), total_raw, total_gz,
             " (PLACEHOLDER terminal)" if stubbed else ""))
    for sym, url, _m, raw, gz in rows:
        print("mkweb:   %-10s %-10s %7d -> %6d" % (url, sym, raw, gz))
    return True


if __name__ == "__main__":
    build(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
